if: branch = master

before_install:
  - sudo apt-get update
  - sudo apt-get install awscli

language: node_js

node_js:
  - "stable"
cache:
  directories:
  - node_modules

script:
  - yarn build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "andrew-fabian-website"
  local_dir: "build"
  skip_cleanup: true
  region: us-west-2

after_deploy:
  - aws cloudfront create-invalidation --distribution-id E1E6NAY17UFOG4 --paths "/*"